// config.js
// Keep only mock/demo data in this module so it can be swapped later with a data-fetcher.

export const kafkaData = {
    lastUpdated: "16:50:01",
    rows: [
        {
            name: "Kafka 1",
            host: "equify-gcp-k1",
            cpu: 8.5,
            memory: 55.0,
            threads: 230,
            connections: 37,
            heapMb: 450,
            topicHealth: "Normal",
            status: "Active",
            exceededThreshold: false,
            topics: [
                { topic: "sms.equ101.trans.created", messages: 10000000 },
                { topic: "sms.equ101.trans.success", messages: 5600000 },
                { topic: "sms.equ101.trans.failed", messages: 5700000 },
                { topic: "sms.equ101.auth.otp_sent", messages: 12500000 },
                { topic: "sms.equ101.auth.otp_verified", messages: 11950000 },
                { topic: "sms.equ101.promo.campaign_sent", messages: 25000000 },
                { topic: "sms.equ101.notif.delivery_update", messages: 3200000 },
                { topic: "sms.equ101.account.pw_reset", messages: 850000 },
                { topic: "sms.equ101.support.ticket_update", messages: 450000 },
                { topic: "sms.equ101.system.maintenance_alert", messages: 95000 },
            ],
        },
        {
            name: "Kafka 2",
            host: "equify-gcp-k2",
            cpu: 45.6,
            memory: 40.6,
            threads: 200,
            connections: 65,
            heapMb: 450,
            topicHealth: "Normal",
            status: "Inactive",
            exceededThreshold: false,
            topics: [],
        },
        {
            name: "Kafka 3",
            host: "equify-gcp-k3",
            cpu: 50.8,
            memory: 78.0,
            threads: 1000,
            connections: 33,
            heapMb: 5,
            topicHealth: "Normal",
            status: "Inactive",
            exceededThreshold: false,
            topics: [],
        },
        {
            host: "equify-gcp-k4",
            timestamp: "2025-08-07T16:30:01",
            componentType: "Kafka",
            name: "Kafka4",
            status: "active",
            cpu: 3.3,
            memory: 90.6,
            threads: 349,
            connections: 58,
            heapMb: 274.33,
            topicHealth: "Warning",
            exceededThreshold: true
        },
        {
            name: "Kafka 5",
            host: "equify-gcp-k5",
            cpu: 12.4,
            memory: 33.2,
            threads: 120,
            connections: 12,
            heapMb: 128,
            topicHealth: "Normal",
            status: "Active",
            exceededThreshold: false,
            topics: []
        },
        {
            name: "Kafka 6",
            host: "equify-gcp-k6",
            cpu: 66.6,
            memory: 72.5,
            threads: 520,
            connections: 92,
            heapMb: 768,
            topicHealth: "Warning",
            status: "Inactive",
            exceededThreshold: true,
            topics: []
        },
        {
            name: "Kafka 7",
            host: "equify-gcp-k7",
            cpu: 0.5,
            memory: 10.2,
            threads: 50,
            connections: 3,
            heapMb: 64,
            topicHealth: "Normal",
            status: "Active",
            exceededThreshold: false,
            topics: []
        },
        {
            name: "Kafka 8",
            host: "equify-gcp-k8",
            cpu: 89.9,
            memory: 95.1,
            threads: 1400,
            connections: 350,
            heapMb: 1024,
            topicHealth: "Warning",
            status: "Inactive",
            exceededThreshold: true,
            topics: []
        },
        {
            name: "Kafka 9",
            host: "aws-kafka-1",
            cpu: 34.2,
            memory: 48.8,
            threads: 310,
            connections: 220,
            heapMb: 256,
            topicHealth: "Normal",
            status: "Active",
            exceededThreshold: false,
            topics: []
        },
        {
            name: "Kafka 10",
            host: "azure-kafka-2",
            cpu: 22.0,
            memory: 12.0,
            threads: 98,
            connections: 44,
            heapMb: 180,
            topicHealth: "Normal",
            status: "Active",
            exceededThreshold: false,
            topics: []
        }
    ],
};
